kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kpng-example
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpng-example
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kpng-daemonset
subjects:
- kind: ServiceAccount
  name: kpng-example
  namespace: psmdb
roleRef:
  kind: ClusterRole
  name: kpng-example
  apiGroup: rbac.authorization.k8s.io
